"""add delivered fields to patient folder

Revision ID: 1f040277a9e0
Revises: 728a7867d177
Create Date: 2026-04-14 12:54:02.423687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f040277a9e0'
down_revision = '728a7867d177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_folders', schema=None) as batch_op:
        batch_op.drop_column('delivered_by')
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
