"""add patient folder workflow v2

Revision ID: 728a7867d177
Revises: 51a707d0eaaa
Create Date: 2026-04-13 21:41:15.344861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728a7867d177'
down_revision = '51a707d0eaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_secretary', sa.String(length=120), nullable=True),
    sa.Column('assigned_major', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_folders_folder_number'), ['folder_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_folders_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_folders_status'), ['status'], unique=False)

    op.create_table('requested_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=150), nullable=False),
    sa.Column('body_part', sa.String(length=150), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('result_pdf', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['patient_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requested_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requested_exams_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requested_exams_status'), ['status'], unique=False)

    op.create_table('workflow_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['patient_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_logs_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_workflow_logs_folder_id'))

    op.drop_table('workflow_logs')
    with op.batch_alter_table('requested_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requested_exams_status'))
        batch_op.drop_index(batch_op.f('ix_requested_exams_folder_id'))

    op.drop_table('requested_exams')
    with op.batch_alter_table('patient_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_folders_status'))
        batch_op.drop_index(batch_op.f('ix_patient_folders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_folders_folder_number'))

    op.drop_table('patient_folders')
    # ### end Alembic commands ###
