"""add recommendation request model

Revision ID: 825447076b60
Revises: 6d7b24817e6f
Create Date: 2026-04-12 22:10:30.153141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825447076b60'
down_revision = '6d7b24817e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_file', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('major_seen', sa.Boolean(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_requests')
    # ### end Alembic commands ###
